In [24]:
import numpy as np
import pandas as pd

In [25]:
data = pd.read_csv("stock_price.csv")
data

Date        Open        High         Low       Close   Adj Close  \
0     29-06-2010   19.000000   25.000000   17.540001   23.889999   23.889999   
1     30-06-2010   25.790001   30.420000   23.299999   23.830000   23.830000   
2     01-07-2010   25.000000   25.920000   20.270000   21.959999   21.959999   
3     02-07-2010   23.000000   23.100000   18.709999   19.200001   19.200001   
4     06-07-2010   20.000000   20.000000   15.830000   16.110001   16.110001   
...          ...         ...         ...         ...         ...         ...   
2411  28-01-2020  568.489990  576.809998  558.080017  566.900024  566.900024   
2412  29-01-2020  575.690002  589.799988  567.429993  580.989990  580.989990   
2413  30-01-2020  632.419983  650.880005  618.000000  640.809998  640.809998   
2414  31-01-2020  640.000000  653.000000  632.520020  650.570007  650.570007   
2415  03-02-2020  673.690002  786.140015  673.520020  780.000000  780.000000   

        Volume  
0     18766300  
1     17187100  
2      8218800  
3      5139800  
4      6866900  
...        ...  
2411  11788500  
2412  17801500  
2413  29005700  
2414  15719300  
2415  47065000  

[2416 rows x 7 columns]

In [26]:
data.shape

(2416, 7)

In [28]:
data.isnull().sum()

Date         0
Open         1
High         0
Low          4
Close        1
Adj Close    1
Volume       0
dtype: int64

In [27]:
x = data[['Date','Open','High','Low','Close','Adj Close',]].values
x

array([['29-06-2010', 19.0, 25.0, 17.540001, 23.889999, 23.889999],
       ['30-06-2010', 25.790001, 30.42, 23.299999, 23.83, 23.83],
       ['01-07-2010', 25.0, 25.92, 20.27, 21.959999, 21.959999],
       ...,
       ['30-01-2020', 632.419983, 650.880005, 618.0, 640.809998,
        640.809998],
       ['31-01-2020', 640.0, 653.0, 632.52002, 650.570007, 650.570007],
       ['03-02-2020', 673.690002, 786.140015, 673.52002, 780.0, 780.0]],
      dtype=object)

In [11]:
y = data[['Volume']].values
y

array([[18766300],
       [17187100],
       [ 8218800],
       ...,
       [29005700],
       [15719300],
       [47065000]], dtype=int64)

In [12]:
from sklearn.impute import SimpleImputer

In [13]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(x[:,1:3])

In [14]:
x[:,1:3]=imputer.transform(x[:,1:3])
x

array([['29-06-2010', 19.0, 25.0, 17.540001, 23.889999, 23.889999],
       ['30-06-2010', 25.790001, 30.42, 23.299999, 23.83, 23.83],
       ['01-07-2010', 25.0, 25.92, 20.27, 21.959999, 21.959999],
       ...,
       ['30-01-2020', 632.419983, 650.880005, 618.0, 640.809998,
        640.809998],
       ['31-01-2020', 640.0, 653.0, 632.52002, 650.570007, 650.570007],
       ['03-02-2020', 673.690002, 786.140015, 673.52002, 780.0, 780.0]],
      dtype=object)

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
label_encode_x=LabelEncoder()
label_encode_y=LabelEncoder()

In [17]:
x[:,0]=label_encode_x.fit_transform(x[:,0])
x

array([[2246, 19.0, 25.0, 17.540001, 23.889999, 23.889999],
       [2319, 25.790001, 30.42, 23.299999, 23.83, 23.83],
       [33, 25.0, 25.92, 20.27, 21.959999, 21.959999],
       ...,
       [2301, 632.419983, 650.880005, 618.0, 640.809998, 640.809998],
       [2374, 640.0, 653.0, 632.52002, 650.570007, 650.570007],
       [166, 673.690002, 786.140015, 673.52002, 780.0, 780.0]],
      dtype=object)

In [18]:
y=label_encode_y.fit_transform(y)
y

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2321, 2298, 1918, ..., 2379, 2283, 2390], dtype=int64)

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

In [21]:
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[42 135.0 136.520004 132.630005 135.550003 135.550003]
 [1312 217.809998 219.990005 214.5 215.470001 215.470001]
 [569 260.5 260.820007 248.020004 250.070007 250.070007]
 ...
 [292 240.490005 242.350006 236.529999 238.929993 238.929993]
 [185 29.950001 31.5 29.5 30.129999 30.129999]
 [1252 255.149994 262.459991 252.419998 260.73999 260.73999]]
[[756 29.309999 29.940001 29.309999 29.940001 29.940001]
 [1446 241.389999 241.550003 233.509995 235.839996 235.839996]
 [928 364.48999 368.76001 360.399994 362.75 362.75]
 ...
 [1365 172.419998 172.949997 164.770004 166.770004 166.770004]
 [907 222.949997 223.380005 209.0 209.259995 209.259995]
 [2339 229.149994 232.440002 224.210007 225.610001 225.610001]]
[1379  820 1794 ...  955 1583 1929]
[ 166 1320 1535  229 1916 2265 1246 1020 1861 2356 1951   92 1611  224
 1287 1622  129  389 2341  269 1762 1464  378  133 1841 1971  791  141
 1960   87   70 1313 2208  825 1132 2347  818 1931 1458  346  889 1520
 2202  424 1696  450  394  608  989  604 17

In [22]:
from sklearn.preprocessing import StandardScaler  #FEATURE SCALING

In [23]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
print(x_train)
print(x_test)

[[-1.67458618 -0.4315509  -0.4380733  -0.43315078 -0.42615642 -0.42615642]
 [ 0.14730613  0.27058034  0.25784586  0.27233301  0.25003848  0.25003848]
 [-0.9185726   0.63254128  0.59826014  0.561179    0.54278559  0.54278559]
 ...
 [-1.31594596  0.46288009  0.44426916  0.46216821  0.44853107  0.44853107]
 [-1.46944397 -1.32225115 -1.31366251 -1.32183469 -1.31810426 -1.31810426]
 [ 0.06123247  0.58717953  0.61193327  0.59909429  0.63306322  0.63306322]]
[[-0.63858959 -1.31084917 -1.30418732 -1.30270978 -1.29972254 -1.29953559]
 [ 0.34924923  0.44467516  0.40802656  0.41631202  0.39183938  0.39186989]
 [-0.39234571  1.46365398  1.43732922  1.48451319  1.43446266  1.43439676]
 ...
 [ 0.23328555 -0.12623448 -0.14704117 -0.16236352 -0.17560196 -0.17551897]
 [-0.42241037  0.29203525  0.26100646  0.20997893  0.1734726   0.17352331]
 [ 1.6277131   0.34335666  0.33431421  0.33802171  0.30779532  0.30783361]]
